### ISSUE TITLE
alac files are not supported (maybe)

### ISSUE THREAD

**Issue by legacychimera247** [knuxify/eartag#27]
i guess alac files are not supported, as they don't show any info?
![Schermata del 2022-09-13 02-32-38](https://user-images.githubusercontent.com/22254556/189782243-19def611-342a-4554-8ebd-e949814e8c89.png)

**Comment by knuxify** [comment]
That's odd... usually unknown formats should be handled by taglib, but here they seem to have been handled by a different backend (judging by the presence of the cover art).

Could you post the command line output from Ear Tag when loading these files?

This could be magic wrongly detecting the file type; try to  run the following commands:

```
python3
(the python interactive prompt will open)
>>> import magic
>>> magic.from_file('/path/to/your/file', mime=True)
```

and post the output of that.

**Comment by knuxify** [comment]
#32 was a similar issue, and it should've been fixed by ce3d42ca0213333b3748e8f65a2248e5718b4691. Could you please test this again with the latest Ear Tag version?

**Comment by legacychimera247** [comment]
hello, now i can actually see some infos, but i can't still see the cover art, maybe i need to open another issue for that?

**Comment by knuxify** [comment]
> now i can actually see some infos, but i can't still see the cover art

That's to be expected, because Ear Tag currently doesn't have a dedicated backends for alac files, meaning that it has to use pytaglib which doesn't support cover art.

I'll probably add a proper backend for it while working on #24.
