### ISSUE TITLE
Ear Tag v3.0 fails to open file(s) or folder and sometimes crashes

### ISSUE THREAD

**Issue by Scotty-Trees** [knuxify/eartag#57]
Just updated to v3.0 of Ear Tag today since it was just released and now unable to use it at all as the title suggests. My flatpak components are fully up to date (Flatpak 1.12.7), and I'm currently running Ubuntu 22.04 LTS under Xorg, but it also crashed under Wayland as well. I have also attempted to restart my system to see if that helped. It did not. 

I get the following error message any time I try to open any file or any folder (i've tried about a dozen different ones) and if I don't recieve the following error message, then the application just crashes and closes itself. 

Perhaps the v.30 build needs a hotfix or news access to new permission via Flatseal, I am not sure, but please let me know if there's any other system info/logs I may be able to provide to help troubleshoot this issue, thank you.

![Screenshot from 2022-12-24 10-14-15](https://user-images.githubusercontent.com/45135187/209442062-3d2da2a9-9231-4f00-8c5e-0fc9420ccde9.png)

Edit: Here's the only issue I found that shows up on Gnome Logs, hopefully this helps:
![Screenshot from 2022-12-24 10-19-22](https://user-images.githubusercontent.com/45135187/209442260-afeac702-805b-48ed-b646-04c26ee0e2f9.png)

**Comment by knuxify** [comment]
The logs you've provided point at this being an issue with the ID3 backend's disc number handling; the backend was rewritten this release, so it makes sense that this could've slipped through. 5c6841a fixes this. I've pushed the hotfix to Flatpak, could you test if this fixes the issue?

(As for the "sometimes crashes" issue - I've noticed something similar during testing, but completely forgot to track down the root cause. I'll open a separate issue for it - #57. If you happen to encounter this issue again, feel free to provide logs.)

**Comment by Scotty-Trees** [comment]
Just updated Ear Tag to the latest release now and unfortunately I still get an error when trying to open a file or a folder. This is the Gnome Log from attempting to open a file after the hotfix was released. Thanks for the reply btw!

![Screenshot from 2022-12-25 10-14-29](https://user-images.githubusercontent.com/45135187/209473468-21d8ea6b-b94a-4500-8e00-e950cf5fb3fd.png)

**Comment by knuxify** [comment]
Oops, that's on me; turns out I didn't apply the patch correctly... it should be fully fixed now. Sorry for the delay.

**Comment by Scotty-Trees** [comment]
No worries, it happens! Just updated again for the newer hotfix and it's working again. Thanks again for the replies and enjoy the rest of your weekend/holidays!

Screenshot just showing things are working normally again! :+1: 
![Screenshot from 2022-12-25 12-01-26](https://user-images.githubusercontent.com/45135187/209476401-ed35ffe2-ab75-4398-8838-ffd8d39f68c6.png)
